# 配置文件请严格遵循 yaml 语法格式，yaml 学习地址:
#  https://ansible-tran.readthedocs.io/en/latest/docs/YAMLSyntax.html
#  http://einverne.github.io/post/2015/08/yaml.html

# 是否强制切换微信号
is_forced_switch: False

# 是否开启自动回复
is_auto_relay: True

# 机器人渠道（1: 图灵机器人，2: 一个AI ,3 : 青云客)
bot_channel: 2

#图灵机器人(http://www.tuling123.com/)免费用户每天可用 100 条。
#请在官网注册并申请 apikey ,userID。
turing_conf:
  apiKey: '2ee6e84a755b4ac2b5b2cc25d992b03a'


# 一个 Al (http://www.yige.ai/),这个功能挺多的，朋友们自行申请，训练。
#  client_token.客户端访问令牌。note: 已填入的这个是博主自己申请的。朋友们最好自行申请并替换。
yigeai_conf:
  client_token: 'D033C925D7AAF369E988D62304FBEC8F'

# 指定自动回复的好友名单。（填：文件传输助手，可回复自己，测试效果）
# - '好友1'
# - '好友2'
auto_reply_names:
  - 'At ease。'
  - '文件传输助手'
  - 'kun.'

#---------------------------群聊助手设置（已完成，正在整理。下个版本发布）--------------------------
auto_reply_group_conf:
  is_open: False # 开启群助手
  # 白名单群
  group_names:
    - 'EverydayWechat 交流群'
  # 艾特标记，只有艾特自己，才发送对应消息。
  is_at: True # 艾特标记
  weather: True # 是否开启天气查询功能


#------------------------ 定时提醒功能--------------------------
alarm_info:
  #True 开启定时提醒，False 关闭
  is_alarm: True
  #定时发送时间
  alarm_timed: '6:20'

girlfriend_infos:

#  如果你有多个好友需要发送，则参照这个样式，复制即可
#  如不需要，则删除或注解下面所有的数据
  - #group_name: 'EverydayWechat 交流群' # 群聊名称，必须要把需要的群聊保存到通讯录。
    wechat_name: '段大羊毛྄ེ很想瘦'
    city_name: 'rizhao'
    dictum_channel : 1
    start_date: '2019-05-28'
    sweet_words: '宝贝今天要开开心心哦！来自你的小林子。。。'
    birthday: "1991-10-24"


